// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-YsnGjxI90dWPItQCZOfzcYE8wxtouwM',
    appId: '1:92645752707:web:ff7b69118a17bd608fc0b6',
    messagingSenderId: '92645752707',
    projectId: 'rentsoft-5ba36',
    authDomain: 'rentsoft-5ba36.firebaseapp.com',
    storageBucket: 'rentsoft-5ba36.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC81rEM0H9MyF3Mldm5ngQr7LQ-BMVjFIY',
    appId: '1:92645752707:android:4676a63673aa1cbe8fc0b6',
    messagingSenderId: '92645752707',
    projectId: 'rentsoft-5ba36',
    storageBucket: 'rentsoft-5ba36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOvbZp9B0mfkCG0IAky6jC6NBXtpNkrXI',
    appId: '1:92645752707:ios:8ac7a404010ef2038fc0b6',
    messagingSenderId: '92645752707',
    projectId: 'rentsoft-5ba36',
    storageBucket: 'rentsoft-5ba36.firebasestorage.app',
    iosBundleId: 'com.example.rentsoftApp',
  );
}
